### ISSUE TITLE
reauthorise error 

### ISSUE THREAD

**Issue by dineshrampalli** [dennisMeeQ/auth0-react-express#11]
After committing logout and performing /people it is not logging in automatically.

**Comment by dennisMeeQ** [comment]
Works for me. 

The only thing that does not seem to work in this context is:
1. logout
2. visit ``/people`` explicitly
3. after being redirected to the login, perform the login

Expected result: you are redirected to ``/people``
Actual result: you are redirected to ``/``

Should be a small fix, I'll happily accept a PR.

**Comment by dennisMeeQ** [comment]
Closing this, no more input.
